name = 'Theme name'
license = "GPL-3.0 License"
licenselink = 'https://github.com/jrilez/logdot/LICENSE'
description = 'A very minimal Hugo theme, inspired by Hyde and the Notable app.'


homepage = 'https://github.com/jrilez/logdot'
demosite = 'https://log.riley.work'

tags = ['blog', 'personal', 'minimal']
features = ['blog', 'search']

[author]
  name = 'Justin Riley'
  homepage = 'https://log.riley.work'
