name = 'Logdot'
license = 'MIT'
licenselink = 'https://github.com/jrilez/logdot/LICENSE'
description = 'Theme description'

homepage = 'https://github.com/jrilez/logdot'
demosite = 'https://log.riley.work'

tags = ['blog']
features = ['']

[author]
  name = 'Justin Riley'
  homepage = 'https://log.riley.work'
